name: CI

on:
  push:
    branches: [ master, main, feature/** ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Build MonoGame Sample (Release)
        run: dotnet build examples/DotCloth.MonoGameSample -c Release --no-restore

