name: CI

on:
  push:
    branches: [ master, main, feature/** ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '9.0.x', '8.0.x' ]
        define: [ '', '-p:DefineConstants=DOTCLOTH_EXPERIMENTAL_XPBD' ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore ${{ matrix.define }}

      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity normal ${{ matrix.define }}

      - name: Build MonoGame Sample (Release)
        run: dotnet build examples/DotCloth.MonoGameSample -c Release --no-restore ${{ matrix.define }}

