name: docs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install DocFX
        run: dotnet tool update -g docfx
      - name: Generate API metadata
        working-directory: docs/docfx
        run: docfx metadata
      - name: Build Docs
        working-directory: docs/docfx
        run: docfx build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/docfx/_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

