name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Compute version from tag
        id: ver
        run: |
          ref="${GITHUB_REF_NAME}"
          ver="${ref#v}"
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack library
        run: dotnet pack src/DotCloth -c Release -o artifacts /p:Version=${{ steps.ver.outputs.version }} --no-build

      - name: Publish to NuGet
        if: env.NUGET_API_KEY != ''
        run: dotnet nuget push artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY" --skip-duplicate

