name: Release (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Update centralized version in Directory.Build.props
        run: |
          ver='${{ inputs.version }}'
          sed -i -E "s|<Version>[^<]+</Version>|<Version>${ver}</Version>|" Directory.Build.props
          echo 'Updated Directory.Build.props version to' "$ver"

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add Directory.Build.props
          git commit -m "chore(release): 🔖 bump to ${{ inputs.version }}"

      - name: Tag release
        run: |
          ver='${{ inputs.version }}'
          git tag -a "v${ver}" -m "DotCloth ${ver}"
          git push origin HEAD:main --follow-tags

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Test (Release)
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack library
        run: dotnet pack src/DotCloth -c Release -o artifacts --no-build

      - name: Publish to NuGet
        if: env.NUGET_API_KEY != ''
        run: dotnet nuget push artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY" --skip-duplicate

